apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: rhopp 
  janus-idp.io/tekton: rhopp
  backstage.io/kubernetes-id: rhopp
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: rhopp
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml